/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import jess.JessException;
import jess.Value;
import jess.ValueVector;

/**
 *
 * @author maiko
 */
public class PanelRespuesta extends javax.swing.JPanel {

    /**
     * Creates new form PanelRespuesta
     */
    public PanelRespuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRespuesta = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(labelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(labelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelRespuesta;
    // End of variables declaration//GEN-END:variables

    void mostrarCamino(ValueVector camino) {
        String respuesta = "El camino que debe seguir es:\n";
        for (int i = 0; i < camino.size(); i++) {
            Value valor;
            try {
                valor = camino.get(i);
                switch (valor.toString()) {
                    case "bm_la_paz":
                        respuesta += " Base militar La Paz\n";
                        break;
                    case "bm_cbba":
                        respuesta += " Base militar Cochabamba\n";
                        break;
                    case "bm_santa_cruz":
                        respuesta += " Base militar Santa Cruz\n";
                        break;
                }
                if (i < camino.size()-1) {
                    respuesta += " - ";
                }
            } catch (JessException ex) {
                Logger.getLogger(PanelRespuesta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        labelRespuesta.setText(respuesta);
    }
}
