/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.ActionListener;

/**
 *
 * @author Nicole
 */
public class PanelTipoCarga extends javax.swing.JPanel {

    /**
     * Creates new form PanelCarga
     */
    public PanelTipoCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPregunta = new javax.swing.JLabel();
        comboBoxRespuesta = new javax.swing.JComboBox<String>();
        imagenPersonalMilitar = new javax.swing.JLabel();
        botonTipoCargaSiguiente = new javax.swing.JButton();
        imagenSuministros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        labelPregunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPregunta.setForeground(new java.awt.Color(255, 255, 255));
        labelPregunta.setText("¿Que tipo de carga desea llevar?");

        comboBoxRespuesta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal Militar", "Suministros" }));
        comboBoxRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRespuestaActionPerformed(evt);
            }
        });

        imagenPersonalMilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/personalMilitar.jpg"))); // NOI18N
        imagenPersonalMilitar.setMaximumSize(new java.awt.Dimension(32767, 32767));
        imagenPersonalMilitar.setMinimumSize(new java.awt.Dimension(800, 600));
        imagenPersonalMilitar.setPreferredSize(new java.awt.Dimension(800, 600));

        botonTipoCargaSiguiente.setText("Siguiente");
        botonTipoCargaSiguiente.setName("botonTipoCargaSiguiente"); // NOI18N
        botonTipoCargaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTipoCargaSiguienteActionPerformed(evt);
            }
        });

        imagenSuministros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/suministros.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagenSuministros)
                            .addComponent(imagenPersonalMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonTipoCargaSiguiente))))
                .addGap(60, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(labelPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(comboBoxRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(imagenPersonalMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenSuministros)
                .addGap(28, 28, 28)
                .addComponent(botonTipoCargaSiguiente)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents
 
    private void comboBoxRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRespuestaActionPerformed

    private void botonTipoCargaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTipoCargaSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTipoCargaSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonTipoCargaSiguiente;
    private javax.swing.JComboBox<String> comboBoxRespuesta;
    private javax.swing.JLabel imagenPersonalMilitar;
    private javax.swing.JLabel imagenSuministros;
    private javax.swing.JLabel labelPregunta;
    // End of variables declaration//GEN-END:variables
 void addOnClickSiguienteEventListener(ActionListener actionListener) {
        this.botonTipoCargaSiguiente.addActionListener(actionListener);
    }
 public int getRespuesta() {
        return comboBoxRespuesta.getSelectedIndex();
    }
}