package ui;

import controladores.ControladorMotorInferencia;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import jess.JessException;

/**
 *
 * @author Nicole
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private PanelUbicacion panelUbicacion;
    private PanelDestino panelDestino;
    private PanelInicio panelInicio;
    private PanelRespuesta panelRespuesta;
    private ControladorMotorInferencia controladorMotorInferencia;

    public VentanaPrincipal(ControladorMotorInferencia controladorMotorInferencia) {
        this.controladorMotorInferencia = controladorMotorInferencia;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planificacion Aerea Militar");
        setMinimumSize(new java.awt.Dimension(800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        panelInicio = new PanelInicio();
        panelInicio.addOnClickEmpezarEventListener(this);

        panelUbicacion = new PanelUbicacion();
        panelUbicacion.addOnClickSiguienteEventListener(this);

        panelDestino = new PanelDestino();
        panelDestino.addOnClickSiguienteEventListener(this);
        
        panelRespuesta = new PanelRespuesta();

        getContentPane().add(panelInicio);
        pack();
    }

    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if (source instanceof JButton) {
            JButton boton = (JButton) source;
            if (boton.getName().equals("botonEmpezar")) {
                cambiarPanel(panelUbicacion);
            }
            if (boton.getName().equals("botonUbicacionSiguiente")) {
                switch (panelUbicacion.getRespuesta()) {
                    case 0:
                        controladorMotorInferencia.evaluar("(ubicacion_inicial (id bm_la_paz))");
                        break;
                    case 1:
                        controladorMotorInferencia.evaluar("(ubicacion_inicial (id bm_cbba))");
                        break;
                    case 2:
                        controladorMotorInferencia.evaluar("(ubicacion_inicial (id bm_santa_cruz))");
                        break;
                }
                cambiarPanel(panelDestino);
            } else if (boton.getName().equals("botonDestinoSiguiente")) {
                switch (panelDestino.getRespuesta()) {
                    case 0:
                        controladorMotorInferencia.evaluar("(ubicacion_destino (id bm_la_paz))");
                        break;
                    case 1:
                        controladorMotorInferencia.evaluar("(ubicacion_destino (id bm_cbba))");
                        break;
                    case 2:
                        controladorMotorInferencia.evaluar("(ubicacion_destino (id bm_santa_cruz))");
                        
                        break;
                }
                cambiarPanel(panelRespuesta);
                try {
                    controladorMotorInferencia.ejecutar();
                    controladorMotorInferencia.getCamino();
                    panelRespuesta.mostrarCamino(controladorMotorInferencia.getCamino());
                } catch (JessException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void cambiarPanel(JPanel panel) {
        getContentPane().removeAll();
        add(panel);
        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
