/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Nicole
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private PanelUbicacion panelUbicacion;
    private PanelDestino panelDestino;
    private PanelInicio panelInicio;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planificacion Aerea Militar");
        setMinimumSize(new java.awt.Dimension(800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void init() {
        panelInicio = new PanelInicio();
        panelInicio.addOnClickEmpezarEventListener(this);
        
        panelUbicacion = new PanelUbicacion();
        panelUbicacion.addOnClickEmpezarEventListener(this);
        
        panelDestino = new PanelDestino();        
        
        getContentPane().add(panelInicio);
        pack();
    }

    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if(source instanceof JButton) {
            JButton boton = (JButton) source;
            if(boton.getName().equals("botonEmpezar")) {
                cambiarPanel(panelUbicacion);
            }
           if(boton.getName().equals("botonSiguiente")) {
               cambiarPanel(panelDestino);
           }           
        }
    }

    private void cambiarPanel(JPanel panel) {
        getContentPane().removeAll();
        add(panel);
        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
